# Generated by Django 4.1.7 on 2023-05-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADAUGDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTGradePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Regulation', models.FloatField()),
                ('Grade', models.CharField(max_length=2)),
                ('Points', models.IntegerField()),
            ],
            options={
                'db_table': 'BTGradePoints',
                'managed': True,
                'unique_together': {('Regulation', 'Grade', 'Points')},
            },
        ),
    ]
