# Generated by Django 4.1.7 on 2023-05-05 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADAUGDB', '0002_btgradepoints'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTMGradePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Regulation', models.FloatField()),
                ('Grade', models.CharField(max_length=2)),
                ('Points', models.IntegerField()),
            ],
            options={
                'db_table': 'BTMGradePoints',
                'managed': True,
                'unique_together': {('Regulation', 'Grade', 'Points')},
            },
        ),
        migrations.CreateModel(
            name='BTMGradesThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Threshold_Mark', models.FloatField()),
                ('Section', models.CharField(default='NA', max_length=2)),
                ('Exam_Mode', models.BooleanField()),
                ('Grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.btmgradepoints')),
                ('RegEventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADAUGDB.btregistrationstatus')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.btmsubjects')),
            ],
            options={
                'db_table': 'BTMGradesThreshold',
                'managed': True,
                'unique_together': {('Grade', 'Subject', 'RegEventId', 'Section', 'Exam_Mode')},
            },
        ),
    ]
