# Generated by Django 4.1.7 on 2023-05-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_btmgradepoints_btmgradesthreshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btmmarksdistribution',
            name='Thresholds',
        ),
    ]
