# Generated by Django 4.1.7 on 2023-05-06 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_btmmarksdistribution_thresholds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btmstudentgrades',
            name='RegId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.btmstudentregistrations'),
        ),
    ]
