# Generated by Django 4.1.7 on 2023-05-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_btmstudentgrades_regid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='btmstudentgradepoints',
            options={'managed': True},
        ),
    ]
