# Generated by Django 4.1.7 on 2023-05-07 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_btmstudentgradepoints_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='btmstudentgradepoints',
            table='BTMStudentGradePointsMV',
        ),
    ]
