# Generated by Django 4.1.7 on 2023-05-07 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_btmstudentgradepoints_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BTMStudentGradePoints',
        ),
    ]
