# Generated by Django 4.1.7 on 2023-05-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_delete_btmstudentgradepoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTMStudentGradePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('sub_id', models.IntegerField()),
                ('SubCode', models.CharField(max_length=10)),
                ('SubName', models.CharField(max_length=100)),
                ('CourseStructure_id', models.IntegerField()),
                ('AYear', models.IntegerField()),
                ('ASem', models.IntegerField()),
                ('BYear', models.IntegerField()),
                ('BSem', models.IntegerField()),
                ('OfferedYear', models.IntegerField()),
                ('Dept', models.IntegerField()),
                ('Grade', models.CharField(max_length=2)),
                ('AttGrade', models.CharField(max_length=2)),
                ('Regulation', models.FloatField()),
                ('Creditable', models.IntegerField()),
                ('Credits', models.IntegerField()),
                ('Course_Credits', models.IntegerField()),
                ('Type', models.CharField(max_length=10)),
                ('Category', models.CharField(max_length=10)),
                ('Points', models.IntegerField()),
                ('GP', models.IntegerField()),
                ('AYASBYBS', models.IntegerField()),
            ],
            options={
                'db_table': 'BTMStudentGradePointsMV',
                'managed': False,
            },
        ),
    ]
